config/routes.rb
Rails.application.routes.draw do
  get 'site/index'

  devise_for :users

  resources :posts do
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  end

  root 'site#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
	has_attached_file :picture
	acts_as_votable
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/

  belongs_to :user

  validates :title, length: { minimum: 2 }, presence: true

  def score
  	self.get_upvotes.size - self.get_downvotes.size
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

	has_many :posts
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!

		#Try doing current_user.posts
		#This will allow only access to posts by current user. 
		#I'm not sure I wan't this. Instead I want posts to be viewed with post owner specified. 

	#GET
	def index
		@posts = current_user.posts
	end

	def show
	end

	#GET
	def new 
		@post = current_user.posts.new
	end

	#POST
	def create
		@post = current_user.posts.new(post_params)
		@post.save
		redirect_to '/posts', notice: 'Post was successfully created'
	end

  def post_params
     params.require(:post).permit(:title, :picture, :user_id)
  end

	def upvote
	  @post = Post.find(params[:id])
	  @post.upvote_by current_user
	  redirect_to '/'
	end

	def downvote
	  @post = Post.find(params[:id])
	  @post.downvote_by current_user
	  redirect_to '/'
	end



  #Work tomorrow
  #Test upvoting
  #Try to integrate Ace
  #Order by community score
  





end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  def index
  	#Change this to by Post.score
  	@posts = Post.order('created_at desc')
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>
    <%= link_to "Change your password", edit_user_registration_path %>

    <% if user_signed_in? %>
      <li>
      <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
    </li>
    <% else %>
      <li>
      <%= link_to('Login', new_user_session_path)  %>  
      </li>
    <% end %>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/posts/index.html.erb
<% if @posts.any? %>
	<% @posts.each do |post| %>
		<h3><%= post.title %></h3>
		<%= image_tag post.picture.url class: 'uploaded-pic' %>
	<% end %>
<% else %>
	No pos8ts yet
<% end %>


<%= link_to 'New post', new_post_path %>

app/views/posts/new.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>

	<%= f.label :picture %>
	<%= f.file_field :picture %>  

	<%= f.submit 'Create post' %>
<% end %>

app/views/site/index.html.erb
<h2>Latest Posts</h2>

<th><%= link_to 'Sign up', new_user_registration_path %></th> 
<th><%= link_to 'Write your own post', new_post_path %></th> 

  <tbody>
	<% @posts.each do |post| %>
		<h3><%= post.title %></h3>
		<%= post.user.email %>   
		<%= image_tag post.picture.url, class: 'uploaded-pic' %>
		<%= link_to "upvote", like_post_path(post), method: :put %>
		<%= link_to "downvote", dislike_post_path(post), method: :put %>
		<h4> Community Score: <%= post.score %></h4>
  <% end %>
  </tbody>
</table>